-- Drop and recreate Users table (Example)
DROP TABLE IF EXISTS users
CASCADE;
CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
DROP TABLE IF EXISTS truck_likes
CASCADE;
CREATE TABLE truck_likes
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  food_truck_id INTEGER REFERENCES food_trucks(id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
DROP TABLE IF EXISTS food_trucks
CASCADE;
CREATE TABLE food_trucks
(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  description TEXT,
  social_media_url VARCHAR(255) NOT NULL
);
